# Generated by Django 5.2.8 on 2025-12-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='accounts/profile_pictures/default_userprofile_pic.avif', upload_to='accounts/profile_pictures/'),
        ),
    ]
