# Generated by Django 5.2.8 on 2025-12-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='accounts/profile_pictures/default_userprofile_pic.png', upload_to='accounts/profile_pictures/'),
        ),
    ]
